name: Nodejs PostgreSQL Image
on:
  push:
    branches: ['master']
    paths-ignore:
      - 'helm/**'
      - 'ecr/**'
jobs:
  node_project:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout destination repository
        uses: actions/checkout@v2
        with:
          repository: robotfree/onexidp-gitops
          ref: main  # Specify the branch you want to update in the destination repository

      - name: Overwrite file in destination repository
        run: |
          cp /argo-ci-cd/app.yaml /onexidp/apps
        # Make sure to replace /path/to/cloned/repository/file and /path/to/destination/repository with the actual paths

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: shujaahmi2l
          author_email: shuja.ahmed@ideatolife.me
          message: "Update single file in destination repository"
          
      - name: Push changes
        uses: EndBug/push-to-another-repository@v1
        with:
          github_token: ${{ secrets.REPO_TOKEN }}
          repository: robotfree/onexidp-gitops
          branch: main

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy to external repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.REPO_TOKEN }}
        with:
          # GitHub Action output files
          source-directory: ecr/
          destination-github-username: robotfree
          destination-repository-name: onexidp-gitops
          user-email: shuja.ahmed@ideatolife.me

      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update values.yaml
        run: |
          cd helm
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' values.yaml 
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add values.yaml
          git commit -m "Update values.yaml"
          git push
