name: Nodejs PostgreSQL Image
on:
  push:
    branches: ['master']
    paths-ignore:
      - 'helm/**'
      - 'ecr/**'
jobs:
  node_project:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create directory for cloned repository
        run: sudo mkdir -p /tmp

      - name: Pull & Push changes to ONYX Github Repo
        run: |
          sudo cp argo-ci-cd/app.yaml /tmp/app.yaml
          sudo cp ecr/ecr-nodejs-postgres-ahjquw.yaml /tmp/ecr-nodejs-postgres.yaml
          cd /tmp
          sudo git clone https://${{ secrets.REPO_TOKEN }}@github.com/robotfree/onexidp-gitops.git main
          ls -la
          sudo cp /tmp/app.yaml /tmp/main/onexidp/apps/app.yaml
          sudo cp /tmp/ecr-nodejs-postgres.yaml /tmp/main/aws-resources/ecr-nodejs-postgres.yaml
          cd main
          ls -la
          sudo git config user.name 'GitHub Actions'
          sudo git config user.email 'actions@github.com'
          sudo git add .
          sudo git commit -m "Updating argo-ci-cd/app.yaml file" || true
          sudo git push https://${{ secrets.REPO_TOKEN }}@github.com/robotfree/onexidp-gitops.git main

      - name: Setup AWS ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push the tagged docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPO }}
          IMAGE_TAG: latest
        run: |
          docker login
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update values.yaml
        run: |
          cd helm
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' values.yaml 
          sudo git config --global user.name 'GitHub Actions'
          sudo git config --global user.email 'actions@github.com'
          sudo git add values.yaml
          sudo git commit -m "Updating values.yaml"
          sudo git push
